### ISSUE TITLE
[Feature Request] Add GNOME 44 Support

### ISSUE THREAD

**Issue by git-Hmmm** [RaphaelRochet/applications-overview-tooltip#29]
Please add support for GNOME 44 to ensure compatibility with the latest version of GNOME and provide users with access to new features and improvements.

**Comment by git-Hmmm** [comment]
I have disabled version validation and it appears to be functioning correctly. It seems that adding the version to the manifest file is the only necessary step.

**Comment by RaphaelRochet** [comment]
That's good news :) Will do.

**Comment by RaphaelRochet** [comment]
Hi,

I have not release a gnome 44 compatible version yet, because of a bug that would sometimes crash the Shell really bad.
Like "segfault" or "general protection fault". 

I *may* have fixed this. Will try it for a little while, and also have to replace a deprecated portion of code to meet GNOME standards.
